Kyuafile: $(SNIPPETS)
	@(echo '-- Autogenerated file';echo 'syntax(2)';echo "test_suite('ashlib')"; \
	x=;for s in $(SNIPPETS) ; do x="$$(echo $$x $$(grep -q -e 'xatf_init' $$s && echo $$s))" ; done ; \
	for s in $$x ; do echo "atf_test_program{name='$$s'}" ; done ; \
	) > $@
