#!/bin/sh
###$_begin-include: utils/rsync-client.sh
set -euf -o pipefail
indexing=false
dryrun=false
info=true

while [ $# -gt 0 ]
do
  case "$1" in
    --index) indexing=true ;;
    --no-index) indexing=false ;;
    --dry-run) dryrun=true ;;
    --no-dry-run) dryrun=false ;;
    --info) info=true ;;
    --no-info) info=false ;;
    *) break;;
  esac
  shift
done

if [ $# -ne 5 ]  && [ $# -ne 4 ] ; then
  cat 1>&2 <<-_EOF_
	Usage:
	   $0 [options] module pwd-file srv src [dst]
	Options:
	--index : create index files
	--dry-run : do not transfer files
	--info : show statistics
	_EOF_
  exit 1
fi

module="$1"
pwdfile="$2"
srv="$3"
src="$4"
if [ $# -eq 5 ] ; then
  dst="$5"
else
  dst=""
fi

[ -n "$dst" ] && dst=$(echo "$dst" | sed -e 's!^/*!/!')
if [ ! -d "$src" ] ; then
  echo "$src: not found" 1>&2
  exit 1
fi


commify() { #$ Format numbers with commas
  #$ :usage: commify value
  #$ :param value: value
  #$ :output: formatted value
  echo $1 | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta'
}

humanize_sz() { #$ Format numbers as friendly sizes
  #$ :usage: humaniz_sz [--bsz=scale] value
  #$ :param --bsz=scale: Optional.  block size
  #$ :param --dec=digits: Optional.  decimal points
  #$ :param value: value to format
  #$ :output: Will output value as a human readable string
  local scale=1 dec=1

  while [ $# -gt 0 ]
  do
    case "$1" in
      --bsz=*) scale=${1#--bsz=} ;;
      --dec=*) dec=${1#--dec=} ;;
      *) break ;;
    esac
    shift
  done
  if [ -z "$1" ] || [ "$1" -eq 0 ] ; then
    echo '0 B'
    return
  fi
  local sz=$(expr "$1" '*' $scale) i a b

  for i in \
    EB:1152921504606846976 \
    PB:1125899906842624 \
    TB:1099511627776 \
    GB:1073741824 \
    MB:1048576 \
    KB:1024
  do
    a=$(echo $i | cut -d: -f1)
    b=$(echo $i | cut -d: -f2)
    if [ $sz -gt $b ] ; then
      awk -vSZ=$sz.0 -vDIV=$b.0 'BEGIN {
	printf("%.'$dec'f '$a'\n", SZ / DIV);
	exit;
      }'
      return
    fi
  done
  echo "$sz B"
}


humanize_ti() { #$ Format numbers in seconds into human readable time intervals
  #$ :usage: humanize_ti [-m|-h|-d] value
  #$ :param -m: Optional.  value given in minutes
  #$ :param -h: Optional.  value given in hours
  #$ :param -d: Optional.  value given in days
  #$ :param value: value to format (in seconds unless option given)
  #$ :output: Will output value as a human readable string
  local scale=1

  while [ $# -gt 0 ]
  do
    case "$1" in
      -m) scale=60 ;;
      -h) scale=3600 ;;
      -d) scale=86400 ;;
      *) break ;;
    esac
    shift
  done
  local c="$1" q="" t
  c=$(expr $c '*' $scale) || :
  local yr=$(expr $(expr 365 '*' 4 + 1) '*' $(expr 86400 / 4))

  if [ $c -ge $yr ] ; then
    t=$(expr $c / $yr)
    echo -n "$q$(commify $t) year"
    [ $t -ne 1 ] && echo -n s
    c=$(expr $c % $yr) || :
    q=", "
  fi
  if [ $c -ge 86400 ] ; then
    t=$(expr $c / 86400)
    echo -n "$q$t day"
    [ $t -ne 1 ] && echo -n s
    c=$(expr $c % 86400) || :
    q=", "
  fi
  if [ $c -ge 3600 ] ; then
    t=$(expr $c / 3600)
    echo -n "$q$t hour"
    [ $t -ne 1 ] && echo -n s
    q=", "
    c=$(expr $c % 3600)
  fi
  if [ $c -ge 60 ] ; then
    t=$(expr $c / 60)
    echo -n "$q$t minute"
    [ $t -ne 1 ] && echo -n s
    q=", "
    c=$(expr $c % 60) || :
  fi
  if [ $c -gt 0 ] ; then
    echo -n "$q$c second"
    [ $c -ne 1 ] && echo -n s
  fi
  echo
}


$info && (
  echo "Started: $(date +"%Y-%m-%d %H:%M:%S") ==="
  echo "Source: $src"
  echo "module: $1"
  echo "server: $srv"
)
start=$(date +%s)

# create permissions
if $indexing ; then
  ipcdir=$(mktemp -d)
  trap "rm -rf $ipcdir" EXIT

  runpipe() {
    local fd="$1" ; shift
    mkfifo "$ipcdir/$fd"
    (
      "$@" < "$ipcdir/$fd" &
    )
    eval "exec $fd>"'$ipcdir/$fd'
    rm -f "$ipcdir/$fd"
  }

  specials() {
    tr '\n' '\0' | ( cd "$1" && cpio -o -H newc -0) | gzip -v > "$2"
  }

  caplist() {
    tr '\n' '\0' | ( cd "$1" && xargs -0 -r getcap ) | gzip -v > "$2"
  }

  faclist() {
    tr '\n' '\0' | ( cd "$1" && xargs -0 -r getfacl -p -n ) | gzip -v > "$2"
  }

  gzlist() {
    gzip -v > "$1"
  }

  # Index tree
  (
    fstree=$(readlink -f "$src")
    meta="$fstree/.meta"

    mkdir -p "$meta"
    runpipe 10 specials "$fstree" "$meta/specials.cpio.gz"
    runpipe 20 caplist "$fstree" "$meta/caps.txt.gz"
    runpipe 30 faclist "$fstree" "$meta/facl.txt.gz"
    runpipe 40 gzlist "$meta/filelist.txt.gz"

    find "$fstree" -print | sed -e "s!^$fstree/!!" -e "s!^$fstree\$!!" | (
    while read -r FPATH
    do
      [ -z "$FPATH" ] && continue
      [ x"$(echo $FPATH | cut -d/ -f1)" = x".meta" ] && continue
      [ -e "$fstree/$FPATH" ] || continue # OK, FPATH doesn't exist

      set - $(stat -c '%u:%g %a %h %i %s %F' "$fstree/$FPATH")
      [ $# -lt 6 ] && continue
      usrgrp="$1" ; mode="$2" ; hcnt="$3" ino="$4" sz="$5"; shift 5
      ftype="$*"

      case "$ftype" in
      directory|regular\ file|regular\ empty\ file)
	echo "$usrgrp $mode $hcnt $ino $FPATH" >&40
	echo "$FPATH" >&20
	echo "$FPATH" >&30
	;;
      *)
	echo "$FPATH" >&10
	;;
      esac
    done)
    #~ exec 10>&- 20>&- 30>&- 40>&-
  )

fi


# Rsync options:
#
#
# -a : archive
# -H : preseve hardlinks
# --delete : delete old files
# -z : compress
# -F : same as --filter='dir-merge /.rsync-filter'
# --no-perms : skip permissions
# --port=18873 : alternatie port
#
# -v : versbose
# --stats : summarize results

# Approach
# http://www.mikerubel.org/computers/rsync_snapshots/#Rsync
# Rotate snapshots, seed with latest from cron daily
# rsync to latest

# RSYNC_PASSWORD - environment variable to store password
export RSYNC_PASSWORD="$(cat "$pwdfile")"
rsync \
	$($dryrun && echo --dry-run) \
	--port=18873 \
	-aHz \
	-F \
	--no-perms \
	--delete \
	$($info && echo --stats) \
	"$src" "${module}@${srv}::${module}${dst}"
rc=$?
$info && echo $(humanize_ti $(expr $(date +%s) - $start))
$info && echo "EXIT: $rc"

exit $rc



# src=rsyncd/ ; srv=nd2 ; module=hassio ; RSYNC_PASSWORD=ziJ4Yi2o
  #~ server: nd2.localnet
  #~ port: 18873
  #~ target: hassio
  #~ username: hassio
  #~ password: ziJ4Yi2o
  #~ ssh_enabled: false

###$_end-include: utils/rsync-client.sh
