#!/bin/sh
. "$(dirname "$0")"/.venv/bin/activate
[ -e "$1" ] && [ ! -x "$1" ] && exec python3 "$@"

if [ -f "$1" ] && [ -x "$1" ] ; then
  cmd="$(readlink -f "$1")" ; shift
  exec "$cmd" "$@"
fi

cmd=$(which "$1")
if [ -n "$cmd" ] ; then
  shift
  exec "$cmd" "$@"
fi

echo "$1: not found" 1>&2
exit 1



